[build-system]
requires = ["scikit-build-core", "pybind11", "cmake"]
build-backend = "scikit_build_core.build"

[project]
name = "torchevent"
version = "0.1.1"
description = "A PyTorch library for event-based data processing"
authors = [{ name = "seokhun.jeon", email = "seokhun.jeon@keti.re.kr" }]
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "torch",
    "tonic",
    "matplotlib",
    "pandas"
]
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[project.urls]
"Homepage" = "https://github.com/devcow85/torchevent"

[tool.scikit-build]
cmake.minimum-version = "3.18"
cmake.args = [
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_CXX_STANDARD=17",
  "-DCMAKE_CXX_FLAGS=--gcc-toolchain=/usr -stdlib=libstdc++ -fopenmp -I/usr/include -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11",
  "-DCMAKE_EXE_LINKER_FLAGS=-fopenmp -L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/x86_64-linux-gnu -lomp",
  "-DCMAKE_SHARED_LINKER_FLAGS=-L/usr/lib/gcc/x86_64-linux-gnu/11 -L/usr/lib/x86_64-linux-gnu -lstdc++"
]